CREATE TABLE IF NOT EXISTS `countries` (
	`country_id` BIGINT NOT NULL AUTO_INCREMENT,
	`iso` VARCHAR(2),
	`iso3` VARCHAR(3),
	`iso_code` INT,
	`fips` VARCHAR(2),
	`display_name` VARCHAR(255),
	`official_name` VARCHAR(255),
	`capital_name` VARCHAR(255),
	`continent_name` VARCHAR(255),
	`currency_code` VARCHAR(3),
	`currency_name` VARCHAR(255),
	`phone_code` INT,
	`region_code` INT,
	`region_name` VARCHAR(255),
	`sub_region_code` INT,
	`sub_region_name` VARCHAR(255),
	`intermediate_region_code` INT,
	`intermediate_region_name` VARCHAR(255),
	`status` VARCHAR(255),
	`development_status` VARCHAR(255),
	`sids` TINYINT,
	`lldc` TINYINT,
	`ldc` TINYINT,
	`area_squared_km` FLOAT,
	`population` BIGINT,
	PRIMARY KEY(`country_id`)
);
